using System.Globalization;
using System.Xml.Linq;

namespace SvgMusic.Scene;

public sealed class DebugSceneRenderer
{
    private static readonly string[] Palette=["#e6194b","#3cb44b","#4363d8","#f58231","#911eb4","#008b8b","#f032e6","#6b8e23","#c71585","#008080","#7b68ee","#9a6324","#b8860b","#800000","#2e8b57","#808000","#d2691e","#000075"];
    public void RenderAll(string input,NotationScene scene,string dir,string name){Render(input,Path.Combine(dir,name+".strokes.svg"),(r,n)=>AddStrokes(r,n,scene));Render(input,Path.Combine(dir,name+".arcs.svg"),(r,n)=>AddCurves(r,n,scene));Render(input,Path.Combine(dir,name+".contours.svg"),(r,n)=>AddContours(r,n,scene));}
    private static void Render(string input,string output,Action<XElement,XNamespace> add){var doc=XDocument.Load(input,LoadOptions.PreserveWhitespace);var root=doc.Root??throw new InvalidOperationException("SVG has no root element.");add(root,root.Name.Namespace);doc.Save(output,SaveOptions.DisableFormatting);}
    private static void AddStrokes(XElement root,XNamespace ns,NotationScene scene){var g=Group(ns,"debug-strokes");foreach(var s in scene.Strokes)g.Add(new XElement(ns+"line",new XAttribute("x1",F(s.Start.X)),new XAttribute("y1",F(s.Start.Y)),new XAttribute("x2",F(s.End.X)),new XAttribute("y2",F(s.End.Y)),new XAttribute("stroke","#00a7d6"),new XAttribute("stroke-width",F(Math.Clamp(s.Width+3,4,12))),new XAttribute("stroke-linecap","round"),new XAttribute("opacity","0.75")));root.Add(g);}
    private static void AddCurves(XElement root,XNamespace ns,NotationScene scene){var g=Group(ns,"debug-curved-strokes");foreach(var c in scene.CurvedStrokes){if(c.Centerline.Count<2)continue;var d="M "+F(c.Centerline[0].X)+" "+F(c.Centerline[0].Y)+string.Concat(c.Centerline.Skip(1).Select(p=>$" L {F(p.X)} {F(p.Y)}"));g.Add(new XElement(ns+"path",new XAttribute("d",d),new XAttribute("fill","none"),new XAttribute("stroke","#d81b60"),new XAttribute("stroke-width","5"),new XAttribute("stroke-linecap","round"),new XAttribute("stroke-linejoin","round"),new XAttribute("opacity","0.82")));}root.Add(g);}
    private static void AddContours(XElement root,XNamespace ns,NotationScene scene){var g=Group(ns,"debug-contours");foreach(var i in scene.Instances){var index=ParsePrototypeIndex(i.PrototypeId);var color=Palette[(index-1)%Palette.Length];var fs=Math.Clamp(Math.Max(i.Width,i.Height)*0.28,14,28);g.Add(new XElement(ns+"rect",new XAttribute("x",F(i.X)),new XAttribute("y",F(i.Y)),new XAttribute("width",F(i.Width)),new XAttribute("height",F(i.Height)),new XAttribute("fill","none"),new XAttribute("stroke",color),new XAttribute("stroke-width","3")),new XElement(ns+"text",new XAttribute("x",F(i.X)),new XAttribute("y",F(Math.Max(fs,i.Y-4))),new XAttribute("font-family","Arial, sans-serif"),new XAttribute("font-size",F(fs)),new XAttribute("font-weight","700"),new XAttribute("fill",color),new XAttribute("stroke","white"),new XAttribute("stroke-width","2"),new XAttribute("paint-order","stroke fill"),$"p{index}"));}root.Add(g);}
    private static XElement Group(XNamespace ns,string id)=>new(ns+"g",new XAttribute("id",id),new XAttribute("pointer-events","none"));
    private static int ParsePrototypeIndex(string id){var dash=id.LastIndexOf('-');return dash>=0&&int.TryParse(id[(dash+1)..],out var v)?Math.Max(1,v):1;}
    private static string F(double v)=>v.ToString("0.###",CultureInfo.InvariantCulture);
}
