using System.Text.Json;using SvgMusic.Scene;
if(args.Length==0){Console.Error.WriteLine("Usage: dotnet run -- <input.svg> [notation-scene.json] [--debug] [--verbose-json]");return 2;}
var input=args[0];var positional=args.Skip(1).Where(x=>!x.StartsWith("--",StringComparison.Ordinal)).ToArray();var output=positional.Length>0?positional[0]:"notation-scene.json";var debug=args.Any(x=>x.Equals("--debug",StringComparison.OrdinalIgnoreCase));var verbose=args.Any(x=>x.Equals("--verbose-json",StringComparison.OrdinalIgnoreCase));var clusterer=new ShapeClusterer();var pipeline=new ScenePipeline(new SvgNormalizer(),clusterer);var(geometry,notation)=pipeline.Run(input);
Console.WriteLine($"GeometricScene shapes       : {geometry.Shapes.Count}");Console.WriteLine($"NotationScene contours      : {notation.Instances.Count}");Console.WriteLine($"NotationScene prototypes    : {notation.Prototypes.Count}");Console.WriteLine($"NotationScene strokes       : {notation.Strokes.Count}");Console.WriteLine($"NotationScene curved strokes: {notation.CurvedStrokes.Count}");Console.WriteLine($"NotationScene ellipses      : {notation.Ellipses.Count} (hollow: {notation.Ellipses.Count(x=>x.IsHollow)})");
foreach(var p in notation.Prototypes){var count=notation.Instances.Count(x=>x.PrototypeId==p.Id);Console.WriteLine($"  {p.Id}: {count} instances; representative={p.RepresentativeShapeId}");}
var compact=new{prototypes=notation.Prototypes.Select(p=>new{id=p.Id,representativeShapeId=p.RepresentativeShapeId,instanceCount=notation.Instances.Count(x=>x.PrototypeId==p.Id),aspectRatio=p.Descriptor.AspectRatio,relativeArea=p.Descriptor.RelativeArea}),instances=notation.Instances,strokes=notation.Strokes,curvedStrokes=notation.CurvedStrokes,ellipses=notation.Ellipses};var options=new JsonSerializerOptions{WriteIndented=true};File.WriteAllText(output,JsonSerializer.Serialize(compact,options));Console.WriteLine($"Written compact JSON: {Path.GetFullPath(output)}");
if(verbose){var v=Path.Combine(Path.GetDirectoryName(Path.GetFullPath(output))??Environment.CurrentDirectory,Path.GetFileNameWithoutExtension(output)+".verbose.json");File.WriteAllText(v,JsonSerializer.Serialize(notation,options));Console.WriteLine($"Written verbose JSON: {v}");}
if(debug){var dir=Path.GetDirectoryName(Path.GetFullPath(input))??Environment.CurrentDirectory;var name=Path.GetFileNameWithoutExtension(input);new DebugSceneRenderer().RenderAll(input,notation,dir,name);Console.WriteLine("Written debug SVGs:");foreach(var suffix in new[]{"strokes","arcs","ellipses","contours"})Console.WriteLine($"  {Path.Combine(dir,name+"."+suffix+".svg")}");var diag=Path.Combine(dir,name+".arc-diagnostics.txt");File.WriteAllLines(diag,clusterer.ArcDiagnostics.Select(d=>$"{d.ShapeId,-10} {d.Result,-6} {d.Reason,-36} {d.Metrics}"));Console.WriteLine($"  {diag}");}
if(Path.GetFileName(input).Equals("shape-clustering-noteheads.svg",StringComparison.OrdinalIgnoreCase)){var ok=geometry.Shapes.Count==100&&notation.Strokes.Count==0&&notation.CurvedStrokes.Count==0&&notation.Ellipses.Count==100;Console.WriteLine(ok?"Fixture check: PASS (100 ellipse-like noteheads)":"Fixture check: FAIL");return ok?0:1;}return 0;
